### Hello World
GET / HTTP/1.1
Host: localhost:7777

### Tutorial - Query params
GET /tutorial/users?search=Maicon HTTP/1.1
Host: localhost:7777

### Tutorial - Route params - PUT
PUT /tutorial/users/1 HTTP/1.1
Host: localhost:7777

### Tutorial - Route params - DELETE
DELETE /tutorial/users/1 HTTP/1.1
Host: localhost:7777

### Tutorial - Body
POST /tutorial/users/maicon HTTP/1.1
Host: localhost:7777
Content-Type: application/json

{
  "username": "Maicon",
  "description": "developer"
}

### Register Dev
POST /devs HTTP/1.1
Host: localhost:7777
Content-Type: application/json

{
  "github_username": "maiconm",
  "techs": "Angular, Ionic, ReactJS, ReactNative, Node.js",
  "latitude": -25.5172205,
  "longitude": -49.2150703
}

### List all developers
GET /devs HTTP/1.1
Host: localhost:7777
Content-Type: application/json


### Search dev
GET /search?latitude=32.4586858&longitude=-110.8571443&techs=ReactJs,%20Angular HTTP/1.1
Host: localhost:7777
Content-Type: application/json
